name: E33UHC
version: 1.1.0
main: fr.jinxss.e33.E33UHC
api-version: 1.21
commands:
  giveRandomRole:
    description: Assigne un rôle aléatoire à un joueur
    usage: /giveRandomRole <joueur>
    permission: e33.give
  givePicto:
    description: Assigne un Picto aléatoire à un joueur
    usage: /giveRandomPicto <joueur>
    permission: e33.give
  picto:
  Level:
  invoke:
    permission: e33.summon
  Team:
    description: Permet de choisir son équipe
    usage: /Team (Create <TeamName> <Color>)
  Grade:
    description: permet de géré les grades des joueurs
    usage: /Grade <Player> <GradeName>
  revive:
    description: permet de revive un/des joueur(s) mort
    permession: e33.revive
